### ISSUE TITLE
Home Page - Fixes Needed

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/pdx-robotics.github.io#10]
Viking Picture is needed, if possible in the header somehow.
Some other things on the home page include: 
- Copyright label at bottom, "Coverr" should be "Cover" or change label entirely
- Black footer has an unrelated paragraph and should be replaced or removed

**Comment by Chana030102** [comment]
"Coverr" is a reference to another website with that name. This can be kept or we can still consider changing/removing the label.

**Comment by philiparola** [comment]
We need to keep attribution until we get our own media for everything.

Field trip!
