### ISSUE TITLE
Projects - Add Gallery

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/pdx-robotics.github.io#26]
~~A gallery for each individual project is needed so we can post images and videos of us working on it.~~
[2019-2-8] This is being changed to a single gallery page instead of unique galleries in each different project for simplicity.

**Comment by philiparola** [comment]
Another idea we can roll into this: we can have the banner images and videos randomly select from a folder

**Comment by Chana030102** [comment]
This is being changed to a single gallery page instead of unique galleries in each different project.
