### ISSUE TITLE
Create projects pages

### ISSUE THREAD

**Issue by philiparola** [pdx-robotics/pdx-robotics.github.io#5]
Create projects landing page and template for individual projects

**Comment by Chana030102** [comment]
Start with a "projects.shtml" that will act as an index. Use html page from issue #14 for actual project page fillers. Such project page examples include "KHR-1.shtml" and "BubbleBee.shtml".

**Comment by Chana030102** [comment]
"projects.shtml" is now a project index. Pages for current projects have been started, but need to be filled with details and pictures.

**Comment by philiparola** [comment]
Closed by commit e4ba885
