### ISSUE TITLE
Home page doesn't scale down to mobile

### ISSUE THREAD

**Issue by geoolson** [pdx-robotics/pdx-robotics.github.io#52]
The calendar and termly don't fit on the screen, and the footer and the header don't fit across the width of the entire page.

**Comment by halyngoc** [comment]
What do you mean by "the footer and the header don't fit across the width of the entire page"?

**Comment by geoolson** [comment]
I posted screenshots on discord. The site loads with the header and footer in focus, but Google calendar and termly don't fit the screen. You can zoom out to see the full view of the Google Calendar, but then the footer and header don't stretch across the screen as they do on the desktop version of the site.

I'm using Google Chrome version 73.0.3683.90 for Android.
