### ISSUE TITLE
Path names for pages

### ISSUE THREAD

**Issue by Chana030102** [pdx-robotics/pdx-robotics.github.io#6]
The following pages have incorrect paths:
> index.shtml
Navigation bar to go to "Get_Involved" should go to "get_invovled.shtml"

> get_involved.shtml
SSI statements paths need to point to same directory for header and table. Currently points to a non-existent folder

**Comment by philiparola** [comment]
Closed by 990655ba5957796e4e4e8107f7fe7b948527f344
